{% set name = "yt-astro-analysis" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_astro_analysis-{{ version }}.tar.gz
  sha256: 201ee329797dc95f80a0c26e7d7f62b662722d44052e1620423869e87d2f41e7

build:
  number: 0
  skip: true   # [py>=312 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython >=0.29.21,<3.0
    - numpy
    - pip
    - python >= 3.7
  run:
    - h5py >=3.1.0
    - more-itertools >=8.4
    - python >=3.7
    - yt >=4.0.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - yt_astro_analysis
    - yt_astro_analysis.cosmological_observation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt_astro_analysis
  summary: yt astrophysical analysis modules extension
  dev_url: https://github.com/yt-project/yt_astro_analysis/
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
    recipe-maintainers:
      - neutrinoceros
      - brittonsmith
