{% set name = "yt-astro-analysis" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yt_astro_analysis-{{ version }}.tar.gz
  sha256: 59307b598be8aab55b94e3b5a3dc185445885006b025fa0da50819e5c45297c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - rockstar-galaxies  # [linux]
  host:
    - cython >=3.0
    - numpy >=1.17.5,<2.0
    - pip
    - python
  run:
    - h5py >=3.1.0
    - more-itertools >=8.4
    - python
    - yt >=4.0.1
    - {{ pin_compatible('numpy') }}
    - rockstar-galaxies  # [linux]

test:
  imports:
    - yt_astro_analysis
    - yt_astro_analysis.cosmological_observation
    - yt_astro_analysis.halo_analysis.halo_finding.rockstar.rockstar_interface  # [linux]
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt_astro_analysis
  summary: yt astrophysical analysis modules extension
  dev_url: https://github.com/yt-project/yt_astro_analysis/
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - cphyc
    - neutrinoceros
    - brittonsmith
