appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: T95r4/mI7710dm8mqVMaYjowczGjgSZx8BkWjhKPUL7cLCTImTZTvj4oWtFwQCJdWAfpluHmDeoxbJliUaU2D9pvUcRqgGwN6AGWImwZR5nJwkfZw1J3GZbiDdJGwsiQyZsuFeOQXT6wT2GlM+giXFwvatCxqBgVJWafG3Ipc03XcHms8pIzrsWSgu+w+PzMmQLE9eyWjDr7uAlTbWz0sFh7L8RqjaOAIcJ7bD5CDeJawN08Fb2uhVbWE3TF7MrQwyEOeGTp28T8zDLRg7far2yfp1jjFWuluacPn+qlxH6mBD0UALommqWJ961dGlYDZ9J+N+J9072+5BLvuV6m/AI5LdQubEUuaKMTbrK+2wpUVnuiNrbgF68Vrk56zeJHP8b3A0X3aNy87TY8oUupkEy1VKGJeZ37+sIu6UbrRszdkhNbmp7qnK8mo23EbLrDZZ6KKteI9tmyho4ZHcKIkWSZ4aj2XTOO294ZKOo5BLhoOUeyMzbjvDP5MjDMdQ0Bsbim9LPhP/gC4kP/hHBZtFMWuFvbcbqVSdUjFRGIoZR3FdQiIWDzQb/VX6OHtc48d1FrA27sH4uq485yBUPKb/ZLfWr3S0obi/heHZ3IfCNsKv5EtkVOeWK9PP4P5CAaIH2xZTpzXtdd6/iu79TFkFLWVO0VFUELBFVtM/Xuy/I=}
